### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by god-damnit** [nots1dd/LiteFM#1]
![image](https://github.com/user-attachments/assets/3a1dc02b-44cb-42a5-8fd7-e1a3ecc41fa5)
**How to Reproduce:** 
* Run litefm without sudo
* Open a restricted directory like root 
* It will show an error
* Switch to any other directory
* Error message persists

![image](https://github.com/user-attachments/assets/0f5c8b77-a42a-488c-bae8-f9ad3a1b1341)
Also, this shows 12.52 GiB for me, not sure what it is. And if its the drive size, its incorrect.

**Comment by nots1dd** [comment]
Ah yes you actually cannot run litefm for a user without sudo this is a known `bug`

Right now the intention for the file man is to be doing everything as fast as possible and doing that without root permissions is just not it.

Let me know if there are any issues with sudo permissions.

For the drive size, run litefm as sudo user and let me know if the incorrect drive size still persists!

**Comment by arora-archit** [comment]
Ahh, alright.
No such bug with sudo, but yeah the drive size is still wrong even with sudo

**Comment by nots1dd** [comment]
@arora-archit 

I see, what type of hard disk is the one that you are running LiteFM on?

And what is the actual disk size?

**Comment by arora-archit** [comment]
its a 512GB M.2 NVMe PCIe 3.0 SSD
even if its running on /home it should be 421 GiB
![image](https://github.com/user-attachments/assets/192d44fc-159d-4203-b1b9-226b00f54498)

**Comment by arora-archit** [comment]
https://files.catbox.moe/bd4338.webm
Encountered another issue while opening non text files.

**Comment by nots1dd** [comment]
> https://files.catbox.moe/bd4338.webm Encountered another issue while opening non text files.

This issue is mentioned in the README, you do not have `$VISUAL` set properly and litefm tries to read that and accordingly open an application that can preview images,

So if you do `export VISUAL=binary/to/app` and use this in your shellrc, it should be working

**Comment by nots1dd** [comment]
> its a 512GB M.2 NVMe PCIe 3.0 SSD even if its running on /home it should be 421 GiB ![image](https://private-user-images.githubusercontent.com/176489846/356895233-192d44fc-159d-4203-b1b9-226b00f54498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTgyMzYsIm5iZiI6MTcyMzM5NzkzNiwicGF0aCI6Ii8xNzY0ODk4NDYvMzU2ODk1MjMzLTE5MmQ0NGZjLTE1OWQtNDIwMy1iMWI5LTIyNmIwMGY1NDQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNzM4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2EzYTU4MzM4NTJlMDcwNTgzNjZmOGE0ZGU2NDA4MzAwZjI4MTBiMGRkOWRlZGQ5MjQ3MjBjYjFjY2Y2Y2ZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iqUim1quyEH9CHgW_7fsXoGf2HhITZDmSsrNkUAaCNA)

Hmm, interesting.

I have not tested it with multiple partitions, but still the number is way off from 41gigs.

Not sure on what the issue might be ill take a look into it and get back to you

Thank you for reporting this bug!

**Comment by arora-archit** [comment]
> > https://files.catbox.moe/bd4338.webm Encountered another issue while opening non text files.
> 
> This issue is mentioned in the README, you do not have `$VISUAL` set properly and litefm tries to read that and accordingly open an application that can preview images,
> 
> So if you do `export VISUAL=binary/to/app` and use this in your shellrc, it should be working

Ahh, alright my bad.

> How much free space is on both those partitions? This actually shows the free space ONLY
![image](https://github.com/user-attachments/assets/d02cc62b-fdd2-4f3b-9075-bb018abb57c0)
Ig its showing info for my root partition. But its stored on my /home partition.

**Comment by nots1dd** [comment]
> > > https://files.catbox.moe/bd4338.webm Encountered another issue while opening non text files.
> > 
> > 
> > This issue is mentioned in the README, you do not have `$VISUAL` set properly and litefm tries to read that and accordingly open an application that can preview images,
> > So if you do `export VISUAL=binary/to/app` and use this in your shellrc, it should be working
> 
> Ahh, alright my bad.
> 
> > How much free space is on both those partitions? This actually shows the free space ONLY
> > ![image](https://private-user-images.githubusercontent.com/176489846/356949986-d02cc62b-fdd2-4f3b-9075-bb018abb57c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDM4NDAsIm5iZiI6MTcyMzQ0MzU0MCwicGF0aCI6Ii8xNzY0ODk4NDYvMzU2OTQ5OTg2LWQwMmNjNjJiLWZkZDItNGYzYi05MDc1LWJiMDE4YWJiNTdjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwNjE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTExYzM5MzBmZThlMTYwNjc1ZGI3ODNkMWMyOTRmNTU2N2RjN2JlMzA5MWQ0ZTczZWNkMjE3YTE1YzMwODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-mpi1f5lzXbEBd3vYWrwXR5ltTJuV_xpzU65S7nHVx8)
> > Ig its showing info for my root partition. But its stored on my /home partition.

Yea so basically it is showing the free space in your root partition as you are in sudo right.. I will have to confirm this but the actual concept of the free disk space is working so that is not an issue.

**Comment by arora-archit** [comment]
> > > > https://files.catbox.moe/bd4338.webm Encountered another issue while opening non text files.
> > > 
> > > 
> > > This issue is mentioned in the README, you do not have `$VISUAL` set properly and litefm tries to read that and accordingly open an application that can preview images,
> > > So if you do `export VISUAL=binary/to/app` and use this in your shellrc, it should be working
> > 
> > 
> > Ahh, alright my bad.
> > > How much free space is on both those partitions? This actually shows the free space ONLY
> > > ![image](https://private-user-images.githubusercontent.com/176489846/356949986-d02cc62b-fdd2-4f3b-9075-bb018abb57c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDM4NDAsIm5iZiI6MTcyMzQ0MzU0MCwicGF0aCI6Ii8xNzY0ODk4NDYvMzU2OTQ5OTg2LWQwMmNjNjJiLWZkZDItNGYzYi05MDc1LWJiMDE4YWJiNTdjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwNjE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTExYzM5MzBmZThlMTYwNjc1ZGI3ODNkMWMyOTRmNTU2N2RjN2JlMzA5MWQ0ZTczZWNkMjE3YTE1YzMwODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-mpi1f5lzXbEBd3vYWrwXR5ltTJuV_xpzU65S7nHVx8)
> > > Ig its showing info for my root partition. But its stored on my /home partition.
> 
> Yea so basically it is showing the free space in your root partition as you are in sudo right.. I will have to confirm this but the actual concept of the free disk space is working so that is not an issue.

even without sudo it shows free space in root partition

**Comment by nots1dd** [comment]
@arora-archit 

Hmm i see. Will take a look at it, this seems like a [priority/low] issue, any other issues you have open a new issue this conversation is becoming too long

Appreciate you for helping out making litefm better!

**Comment by nots1dd** [comment]
@arora-archit 

The issue has been noted and I have made the function a bit better,

It now prints `free space / total space SIZE` this format in the ncurses window

![image](https://github.com/user-attachments/assets/e20416dd-9d81-4983-b1a1-a36184658fa6)

These functions however, check the `/` directory by default so your `/home` space will NOT be detected. I do not want to over-complicate this function to check for the maximum space partition and display that (seems unnecessary imo)

So with this commit `https://github.com/nots1dd/LiteFM/commit/aa68bf3b352ddbb9f197e2bee2d25877c232c454` I will be closing this issue.

Thanks again for reporting this!
