### ISSUE TITLE
UI cleanup

### ISSUE THREAD

**Issue by nots1dd** [nots1dd/LiteFM#4]
I tried to make the UI not horrible but needless to say, it is certainly not the best and lacks quite a lot in this department

This issue requires you to make sure that:

-> There is no text overflow of any inode name in litefm

-> Any error that just gets printed onto the screen disregarding curses display should be handled gracefully

-> Any UI tweaks that **YOU DEEM IS NEEDED** with a valid explanation in the PR

Refer to [CONTRIBUTION](https://github.com/nots1dd/litefm/blob/main/CONTRIBUTION.md) for more

**Comment by awmc000** [comment]
I'm interested and have worked with ncurses recently, I would like to take this on.

**Comment by nots1dd** [comment]
Sure, make sure you read through CONTRIBUTION.md before making a PR

In general the issue is slightly vague so in the PR, list all UI changes and also for each commit you make, do write a CHANGELOG file

**Comment by awmc000** [comment]
```
[alex@Alex LiteFM]$ ./build.sh
====================
      LiteFM        
====================
Building for arch...
Detected display server: wayland
✔ Package ncurses is already installed.
✔ Package cmake is already installed.
✔ Package make is already installed.
✔ Package libarchive is already installed.
✔ Package libyaml is already installed.
✔ Package rsync is already installed.
✔ Package pkg-config is already installed.
✔ Package sdl2 is already installed.
✔ Package sdl2_mixer is already installed.
All required packages are already installed.
Nerd Fonts are installed and available.
Enter the type of build (cmake, meson, or make): make
Running make build...
make: *** No rule to make target 'src/signalhandling.o', needed by 'litefm'.  Stop.
Build failed.
```

I have this error when I attempt to build the program on Arch Linux. I notice that there is a header, `signalhandling.h`, but not a `signalhandling.c`, and maybe this is why that module is not being compiled. How should I proceed?

**Comment by awmc000** [comment]
It appears that `signalhandling.c` is mentioned in the `Makefile` but is not included in the repository. Does that need to be added, or maybe I need to switch branch or something?

Thanks in advance.

**Comment by nots1dd** [comment]
@awmc000 

The issue is that the Makefile is just deprecated for now (will update it soon)

How to fix:

-> Remove `src/signalhandling.c` as that has been removed

(OR)

-> Use CMake or Meson to build litefm, they are tested and upto date

**Comment by awmc000** [comment]
Thank you, have now built and used the program a bit. I see the overflow of folder/directory names that you mean and have begun analyzing the code and trying to think of ways to handle this.

**Comment by nots1dd** [comment]
@awmc000 

Thats great! Feel free to ask doubts here regarding the codebase and the logical implementation

**Side Note:**

LiteFM is going through a massive code refactor and a lot of changes/commits are to be expected.

Do make sure that you stay upto date with the codebase in order to contribute

There is already a quite rigid and plain implementation of trying to avoid overflow but it is crude at best

It should be in the `print_items` function in lfm.c

You can start there as a ref point

**Comment by awmc000** [comment]
![image](https://github.com/user-attachments/assets/58ccfea6-4163-4dec-858b-55fd5d9daa69)
Still working on this, but as an update, have made some changes that prevent some of the overflow.

**Comment by nots1dd** [comment]
@awmc000 

Thats great to see! Hopefully understanding the codebase did not prove to be too tough, if am not wrong fixing the rest should also not be too much of a hassle.

Any queries regarding how things work are always welcome but do make sure to note all changes in a changelog file for clear understanding of the changes intended.

**Comment by awmc000** [comment]
Thanks for your help. I've started keeping a changelog and am continuing to work on this in little bits in my free time. Hope to be done my PR within a few weeks, I hope that is an acceptable timeline.

**Comment by awmc000** [comment]
![image](https://github.com/user-attachments/assets/1d96f717-c987-413c-8f1a-1f0221a9e6b3)
Just an observation, multi-byte Unicode characters cause the length caps to be hit faster, so strings get truncated shorter. My checks for length etc. all rely on size in bytes as I believe your code does. But I wonder if there are ways to address this...

**Comment by awmc000** [comment]
-> Any error that just gets printed onto the screen disregarding curses display should be handled gracefully

Initially, I could recreate/trigger this problem easily by scrolling over archives that had spaces in their filename. But I fixed that as far as I can tell, just added single quotes to the archive commands so that spaces in a filename don't enter the command as multiple arguments. 

Now I need to find other ways to trigger this issue. Do you know of any?

**Comment by nots1dd** [comment]
> ![image](https://github.com/user-attachments/assets/1d96f717-c987-413c-8f1a-1f0221a9e6b3)
> Just an observation, multi-byte Unicode characters cause the length caps to be hit faster, so strings get truncated shorter. My checks for length etc. all rely on size in bytes as I believe your code does. But I wonder if there are ways to address this...

Yea i have noticed this as well, might have to look into locale.h header and how to detect CJK chars, for now lets stick with a fixed limit for all chars

**Comment by nots1dd** [comment]
> > -> Any error that just gets printed onto the screen disregarding curses display should be handled gracefully
> 
> Initially, I could recreate/trigger this problem easily by scrolling over archives that had spaces in their filename. But I fixed that as far as I can tell, just added single quotes to the archive commands so that spaces in a filename don't enter the command as multiple arguments. 
> 
> Now I need to find other ways to trigger this issue. Do you know of any? 

Umm not sure about other errors, I can tell you where to look though

If for any form of error handling, there is an `fprintf` or `printf` command, that will cause a similar issue

Also if we are forking and the child proc is running a command that prints information onto the terminal we have to capture that text using `popen` 

I believe searching for such cases should be enough if you have more doubts or queries regarding this feel free to ask

**Comment by nots1dd** [comment]
This issue has been resolved to a major extent, will make a new UI related issue if needed regarding other UX or design QOL changes that need to be made
